import express from "express";
import AppController from "./controller/appController";

const router = express.Router();

// router.get("/slots", AppController.slots);
router.post("/api/login", AppController.Login);
router.post("/api/pending", AppController.RegisterPending);
router.get("/api/student", AppController.GetStudents);
router.get("/api/pending", AppController.GetPendingStudents);
router.post("/api/student/:id", AppController.AcceptStudent);
router.delete("/api/pending/:id", AppController.RejectStudent);
router.get("/api/course", AppController.GetCourses);
router.get("/api/branch", AppController.GetBranches);
router.get("/api/batch", AppController.GetBatches);
router.get("/api/time", AppController.GetTime);
router.get("/api/studentDetails/:id", AppController.GetStudentById);
router.post("/api/student/paststudent/:id", AppController.DeleteStudent);
router.post("/api/payDues", AppController.PayDues);
router.get("/api/batches", AppController.GetAllBatches);
router.post("/api/batches", AppController.CreateBatch);
router.put("/api/batches/:id", AppController.UpdateBatch);
router.delete("/api/batches/:id", AppController.DeleteBatch);
router.get("/api/courses", AppController.GetAllCourses);
router.post("/api/courses", AppController.CreateCourse);
router.put("/api/courses/:id", AppController.UpdateCourse);
router.delete("/api/courses/:id", AppController.DeleteCourse);
router.get("/api/branches", AppController.GetAllBranches);
router.post("/api/branches", AppController.CreateBranch);
router.put("/api/branches/:id", AppController.UpdateBranch);
router.delete("/api/branches/:id", AppController.DeleteBranch);
router.get("/api/admin", AppController.GetAllAdmin);
router.post("/api/admin", AppController.CreateAdmin);
router.put("/api/admin/:id", AppController.UpdateAdmin);
router.delete("/api/admin/:id", AppController.DeleteAdmin);
router.put("/api/changePassword", AppController.ChangePassword);
router.get("/api/students/me", AppController.GetUserDetails);
router.put("/api/updatestudents/:id", AppController.UpdateStudent);
router.post("/api/leave/apply", AppController.ApplyLeave);
router.put("/api/leave/approve/:id", AppController.ApproveLeave);
router.delete("/api/leave/reject/:id", AppController.RejectLeave);
router.get("/api/leave/pendingleave", AppController.GetPendingLeaves);
router.get("/api/course/report", AppController.CourseReport);
router.get("/api/batch/report", AppController.BatchReport);
router.get("/api/branch/report", AppController.BranchReport);
router.get("/api/paststudent/report", AppController.PastStudentReport);
router.get("/api/dues/report", AppController.DuesReport);
router.get("/api/leavestudent", AppController.GetLeaveStudents);
router.get("/api/registration", AppController.RegistrationReport);
router.get("/api/leaveReport", AppController.LeaveStudentReport);
router.get("/api/cashBook", AppController.GetCashBook);
router.get("/api/leavestudentDetails/:id",AppController.GetLeaveStudentDetails)
export default router;
